dist: bionic
language: python
cache: pip
matrix:
  allow_failures:
    - python: 'nightly'
  include:
  - python: 'nightly'
    env: TEST_SUITE=suite_3_9

before_install:
- pip install -r requirements/dev.txt
install:
- python setup.py test
script:
- python theHarvester.py -d apple.com -b baidu,bing,bufferoverun,certspotter,crtsh,dnsdumpster,dogpile,duckduckgo,exalead,linkedin,netcraft,intelx,threatcrowd,trello,twitter,virustotal,yahoo,rapiddns
  -l 200
- pytest
- flake8 . --count --show-source --statistics
- mypy --pretty theHarvester/discovery/*.py